### ISSUE TITLE
DIVI Theme kompatibilität

### ISSUE THREAD

**Issue by TSSimonSemmler** [vendidero/trusted-shops-easy-integration-for-woocommerce#76]
Hi @dennisnissle 

ein Kunde beschwert sich, dass bei Benutzung des DIVI Themes keine Trustcard im Checkout angezeigt wird. Ich habe nach einer Testinstanz gefragt, da wir keinen Zugriff auf eine DIVI Theme Lizenz haben. Ich wollte aber parallel mal bei dir nachfragen, ob du zufällig Zugriff auf eine DIVI Theme Lizenz hast?

Viele Grüße,
Simon

**Comment by dennisnissle** [comment]
Hi @TSSimonSemmler,

nein, ich habe leider keine Divi-Test-Lizenz aber wenn die Trustcard nicht angezeigt wird, kann das nur an einem der folgenden Punkte liegen:

1. Der Hook `woocommerce_thankyou` wird auf der Danke-Seite nicht ausgeführt oder die Danke-Seite wird "umgangen".
2. Ein JS-Problem liegt vor, sodass das Script nicht (richtig) geladen werden kann
3. Die Danke-Seite wird (über einen redirect o.ä.) schnell hintereinander aufgerufen, sodass das Setzen des Meta-Datums (damit die Trustcard nur beim ersten Aufruf angezeigt wird) das Problem verursacht.

Grüße

**Comment by TSSimonSemmler** [comment]
Hi @dennisnissle 

danke für deine Rückmeldung. Ich schätze das Problem ist, dass der Hook wird aus irgendeinem Grund nicht gesetzt. Der Kunde ist aber nun manuell integriert und da es keine einfache Möglichkeit gibt, an dieses Theme zu kommen, schließe ich diesen Issue erstmal. 

Grüße
